#!/bin/bash


# Validator transformer plugin using kubeconform
# https://github.com/yannh/kubeconform
#
# Assumes that kubeconform is available from $PATH
#
# Reads Kubernetes resources from stdin
# Validates them and output in the stdout
#
# Example execution:
# cat <raw K8s yaml> | ./kustomize/plugin/someteam.example.com/v1/validator/Validator

if ! [ -x "$(command -v kubeconform)" ]; then
  echo "Error: kubeconform is not installed."
  exit 1
fi

temp_file=$(mktemp).yaml
output_file=$(mktemp).yaml
cat - > $temp_file

kubeconform $temp_file > $output_file

if [ $? -eq 0 ]; then
    cat $temp_file
    rm $temp_file $output_file
    exit 0
fi

cat $output_file
rm $temp_file $output_file
exit 1
